
DATA_PATH = "../data/phpSSK7iA.csv"
EXPERIMENT_NAME = "tr1"
EXPERIMENT_PATH = "../exp/" + EXPERIMENT_NAME

PREPROCESS = False
REMOVE_DUPLICATES = True
REMOVE_ZERO_COLUMNS = True
REMOVE_CONSTANT_COLUMNS = True
REMOVE_LOW_VARIANCE_COLUMNS = True
VARIANCE_THRESHOLD = 0.01

TEST_SIZE = 0.15
VAL_SIZE = 0.15
RANDOM_STATE = 42
STRATIFY = True
NORMALIZATION_METHOD = 'standard'
APPLY_FEATURE_SELECTION = True
FEATURE_SELECTION_METHOD = ['corr', 'mi', 'rf']
TOP_N_FEATURES = 128

BATCH_SIZE = 256
NUM_WORKERS = 0
SHUFFLE = True
EPOCHS = 100

USE_WANDB = True
WANDB_PROJECT = "zneus1"
WANDB_ENTITY = "eakosh-"

LEARNING_RATE = 0.0005
WEIGHT_DECAY = 3e-3
DROPOUT = 0.4
APPLY_EARLY_STOPPING_PATIENCE = True
EARLY_STOPPING_PATIENCE = 20
SAVE_BEST_MODEL = True
MODEL_CHECKPOINT_PATH = EXPERIMENT_PATH + "/best_model.pth"