
DATA_PATH = "../data/phpSSK7iA.csv"
EXPERIMENT_NAME = "run_01_f_all"
EXPERIMENT_PATH = "../exp/" + EXPERIMENT_NAME

PREPROCESS = True
REMOVE_DUPLICATES = True
REMOVE_ZERO_COLUMNS = True
REMOVE_CONSTANT_COLUMNS = True
REMOVE_LOW_VARIANCE_COLUMNS = True
VARIANCE_THRESHOLD = 0.01

TEST_SIZE = 0.20
VAL_SIZE = 0.20
RANDOM_STATE = 42
STRATIFY = True
NORMALIZATION_METHOD = 'standard'
APPLY_FEATURE_SELECTION = True
FEATURE_SELECTION_METHOD = ['corr', 'mi', 'rf']    #corr, mi, rf
TOP_N_FEATURES = 64

BATCH_SIZE = 256
NUM_WORKERS = 0
SHUFFLE = True
EPOCHS = 100

USE_WANDB = True
WANDB_PROJECT = "zneus1"
WANDB_ENTITY = "eakosh-"

LEARNING_RATE = 0.001
APPLY_EARLY_STOPPING_PATIENCE = False
EARLY_STOPPING_PATIENCE = 10
SAVE_BEST_MODEL = True
MODEL_CHECKPOINT_PATH = EXPERIMENT_PATH + "/best_model.pth"